export const en = {
  appShell: {
    trayOpen: "Open Notei",
    trayNewNote: "New note",
    trayNewReminder: "New reminder",
    trayNewEvent: "New event",
    trayQuit: "Quit",
    quitDialogTitle: "Unsaved changes",
    quitDialogMessage: "You have unsaved changes. Save before quitting?",
    saveAndQuit: "Save & Quit",
    quitWithoutSaving: "Quit without saving",
    cancel: "Cancel",
  },
  sidebar: {
    meetings: "Meetings",
    personal: "Personal",
    calendar: "Calendar",
    reminders: "Reminders",
    templates: "Templates",
    archive: "Archive",
    settings: "Settings",
  },
  titlebar: {
    searchTitle: "Search (Ctrl+K)",
    searchAria: "Search",
    lightMode: "Light mode",
    darkMode: "Dark mode",
    windowControls: "Window controls",
    minimize: "Minimize",
    restore: "Restore",
    maximize: "Maximize",
    close: "Close",
    searchPlaceholder: "Search notes...",
    searchHint: "Search by title, tags, participants or content. Results appear in the list.",
  },
  notes: {
    meetingNotes: "Meeting notes",
    personalNotes: "Personal notes",
    newNote: "New note",
    exportAsZip: "Export as ZIP",
    loading: "Loading...",
    failedToLoad: "Failed to load",
    failedToCreate: "Failed to create",
    noNotesYet: "No notes yet. Create one to get started.",
    open: "Open",
    pinToTop: "Pin to top",
    unpin: "Unpin",
    archive: "Archive",
    exportAsMarkdown: "Export as Markdown",
    delete: "Delete",
    untitled: "Untitled",
    noContent: "No content",
    participants: "participants",
    selectNoteOrCreate: "Select a note or create a new one",
    noteNotFound: "Note not found",
    title: "Title",
    unsaved: "Unsaved",
    save: "Save",
    export: "Export",
    share: "Share",
    exportAsPng: "Export as PNG",
    exportAsMarkdownMenu: "Export as Markdown",
    copyAsMarkdown: "Copy as Markdown",
    copyAsImage: "Copy as image (PNG)",
    revealInFolder: "Reveal in folder",
    saveOpenFile: "Save / Open file",
    openApp: "Open",
    cannotCapture: "Cannot capture content",
    exportFailedOrCancelled: "Export failed or cancelled",
    copyFailed: "Copy failed",
    close: "Close",
  },
  reminders: {
    today: "Today",
    scheduled: "Scheduled",
    overdue: "Overdue",
    completed: "Completed",
    all: "All",
    list: "List",
    newReminder: "New Reminder",
    items: "item",
    itemsPlural: "items",
    quickAddPlaceholder: "Quick Add: Call team tomorrow 15:00, in 2h...",
    noReminders: "No reminders",
    markIncomplete: "Mark incomplete",
    complete: "Complete",
    snooze1h: "Snooze 1 hour",
    edit: "Edit",
    reminder: "Reminder",
    reminderTitle: "Reminder title",
    optionalNotes: "Optional notes",
    linkNote: "Link note",
    none: "None",
    when: "When",
    due: "Due",
    remind: "Remind",
    atTime: "At time",
    fiveMinBefore: "5 min before",
    fifteenMin: "15 min",
    oneHour: "1 hour",
    in30m: "In 30m",
    in2h: "In 2h",
    tomorrow9: "Tomorrow 9:00",
    repeat: "Repeat",
    daily: "Daily",
    weekly: "Weekly",
    monthly: "Monthly",
    yearly: "Yearly",
    priority: "Priority",
    low: "Low",
    medium: "Medium",
    high: "High",
  },
  calendar: {
    today: "Today",
    tomorrow: "Tomorrow",
    next7Days: "Next 7 days",
    later: "Later",
    allDay: "All day",
    agenda: "Agenda",
    importIcs: "Import .ics",
    exportIcs: "Export .ics",
    newEvent: "New event",
    previous: "Previous",
    next: "Next",
    weekOf: "Week of",
    newEventModal: "New event",
    editEventModal: "Edit event",
    eventTitle: "Event title",
    optionalNotes: "Optional notes",
    optionalLocation: "Optional location",
    when: "When",
    localTime: "Local time",
    allDayLabel: "All day",
    start: "Start",
    end: "End",
    now: "Now",
    duration: "Duration",
    min15: "15 min",
    min30: "30 min",
    min45: "45 min",
    hour1: "1 hour",
    hours2: "2 hours",
    custom: "Custom",
    nextWeek: "Next week",
    morning9: "Morning 09:00",
    afternoon14: "Afternoon 14:00",
    sameDay: "Same day",
    remindMe: "Remind me",
    fiveMinBefore: "5 min before",
    tenMinBefore: "10 min before",
    thirtyMinBefore: "30 min before",
    oneHourBefore: "1 hour before",
    oneDayBefore: "1 day before",
  },
  export: {
    exportAsZip: "Export as ZIP",
    selectNotesInclude: "Select notes to include. The ZIP will contain Markdown files per note; optionally JSON.",
    includeJson: "Include JSON",
    includePngPerNote: "Include PNG per note",
    progressFormat: "{current}/{total} – {message}",
    exportingNote: "Exporting {title}...",
    writingZip: "Writing ZIP...",
    pngFailedFor: "PNG failed for:",
    selectAll: "Select all",
    selectAtLeastOne: "Select at least one note",
    exportFailedOrCancelled: "Export failed or cancelled",
    cancelExport: "Cancel export",
    exporting: "Exporting...",
    exportZip: "Export ZIP",
  },
  settings: {
    title: "Settings",
    theme: "Theme",
    system: "System",
    light: "Light",
    dark: "Dark",
    general: "General",
    launchAtStartup: "Launch at startup",
    enabled: "Enabled",
    disabled: "Disabled",
    runInBackground: "Run in background",
    runInBackgroundHint: "When on, closing the window minimizes to the system tray instead of quitting.",
    autosave: "Autosave",
    off: "Off",
    afterDelay: "After delay",
    onFocusChange: "On focus change",
    delayMs: "Delay (ms)",
    export: "Export",
    exportPngAlwaysLight: "Export PNG always in light theme",
    includeBrandHeader: "Include brand header on PNG export",
    defaultFormat: "Default format",
    failedToLoad: "Failed to load settings",
    autostartFailed: "Failed to update. Check system startup settings.",
  },
  dialogs: {
    apply: "Apply",
    cancel: "Cancel",
  },
  commandPalette: {
    placeholder: "Search commands...",
    noCommandsFound: "No commands found",
    createNote: "Create note",
    searchNotes: "Search notes",
    toggleTheme: "Toggle theme",
    exportNote: "Export note",
    createReminder: "Create reminder",
    createEvent: "Create event",
    goToCalendar: "Go to Calendar",
    goToReminders: "Go to Reminders",
    goToMeetings: "Go to Meetings",
    goToPersonal: "Go to Personal",
    commandPaletteAria: "Command palette",
  },
  common: {
    save: "Save",
    cancel: "Cancel",
    delete: "Delete",
    close: "Close",
    back: "Back",
    untitled: "Untitled",
    loading: "Loading...",
    none: "None",
  },
  templates: {
    title: "Templates",
    meeting: "Meeting",
    meetingDesc: "Agenda, notes, decisions, action items",
    routine: "Routine",
    routineDesc: "Daily or weekly routine checklist",
    journal: "Journal",
    journalDesc: "Reflection and journal entry",
    tasks: "Tasks",
    tasksDesc: "Task list with priorities",
    agenda: "Agenda",
    notes: "Notes",
    decisions: "Decisions",
    actionItems: "Action Items",
    morning: "Morning",
    evening: "Evening",
    toDo: "To do",
  },
  archive: {
    title: "Archive",
    restoreAll: "Restore all",
    noArchivedNotes: "No archived notes.",
    restore: "Restore",
  },
  editorToolbar: {
    bold: "Bold (Ctrl+B)",
    italic: "Italic (Ctrl+I)",
    underline: "Underline (Ctrl+U)",
    strikethrough: "Strikethrough",
    heading1: "Heading 1",
    heading2: "Heading 2",
    heading3: "Heading 3",
    quote: "Quote",
    code: "Code",
    codeBlock: "Code block",
    link: "Link",
    bulletList: "Bullet list",
    orderedList: "Ordered list",
    checklist: "Checklist",
    linkPlaceholder: "https://",
    apply: "Apply",
  },
  share: {
    instructions: "Open the app, paste the image (Ctrl+V or Cmd+V), then send.",
  },
} as const;

export type Strings = typeof en;
